<?php

/**
 * BaseBarbaraList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Students
 * 
 * @method Doctrine_Collection getStudents() Returns the current record's "Students" collection
 * @method BarbaraList         setStudents() Sets the current record's "Students" collection
 * 
 * @package    barbara
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBarbaraList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('barbara_list');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BarbaraStudent as Students', array(
             'local' => 'id',
             'foreign' => 'list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}