<?php

/**
 * BarbaraList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    barbara
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BarbaraList extends BaseBarbaraList
{
  public function __toString()
  {
    return "List {$this->id}";
  }

  public static function getRecentLists($max=3)
  {
    return BarbaraListTable::getInstance()
      ->createQuery('a')
      ->limit($max)
      ->orderBy('updated_at DESC')
      ->execute();
  }

  public static function saveList($students, $listID=null)
  {
    // Get the list
    if ($listID)
    {
      $list = BarbaraListTable::getInstance()->findOneById($listID);
      // Check if the students array has changed
      $change = false;
      if (count($list->Students) <> count($students))
      {
        $change = true;
      }
      else
      {
        foreach ($list->Students as $student)
        {
          if (array_search($student->name, $students) === false)
          {
            $change = true;
            break;
          }
        }
      }
      if (!$change)
        return $list;
      $list->Students->delete();
      $list->save();
    }
    else
    {
      $list = new BarbaraList;
      $list->save();
    }

    // Save each student in the database
    foreach ($students as $studentName)
    {
      if (!$studentName)
        continue;
      $student = new BarbaraStudent;
      $student->name = $studentName;
      $student->list_id = $list->id;
      $student->save();
    }

    // Save the list
    $list->save();

    return $list;
  }

  public function getFormattedDate()
  {
    $dt = new DateTime(parent::getUpdatedAt());
    return $dt->format('m/d/Y');
  }
}