<?php

/**
 * BarbaraStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BarbaraStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BarbaraStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BarbaraStudent');
    }
}